PolicyManagementModule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('security.urls')),
    path('', include('django.contrib.auth.urls'))
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('access-denied', views.access_denied, name='access-denied'),
]

security/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create-policy', views.create_policy, name='create_policy'),
    path('edit-policy/<int:pk>', views.edit_policy, name='edit_policy'),
    path('policy-list', views.view_policies, name='view_policies'),
    path('create-risk', views.create_risk, name='create_risk'),
    path('edit-risk/<int:pk>', views.edit_risk, name='edit_risk'),
    path('risk-list', views.view_risks, name='view_risks'),
    path('create-compliance-standard', views.create_compliance_standard, name='create_compliance_standard'),
    path('edit-compliance-standard/<int:pk>', views.edit_compliance_standard, name='edit_compliance_standard'),
    path('compliance-standard-list', views.view_compliance_standard, name='view_compliance_standard'),
    path('policy/<int:pk>/policy-version-list', views.view_policy_versions, name='view_policy_versions'),
    path('view-policy-version/<int:pk>', views.view_policy_version, name='view_policy_version'),
    path('edit-policy-version/<int:pk>', views.edit_policy_version, name='edit_policy_version'),
    path('rollback-policy-version/<int:pk>', views.rollback_policy_version, name='rollback_policy_version'),
    path('view-policy-acknowledgment', views.view_policy_acknowledgment, name='view_policy_acknowledgment'),
    path('view-policy/<int:pk>', views.view_policy, name='view_policy'),
    path('policy/<int:pk>/policy-acknowledgment-list', views.view_policy_acknowledgments, name='view_policy_acknowledgments'),
    path('download-ack-report/<int:pk>', views.download_ack_report, name='download_ack_report'),
    path('submit-policy/<int:pk>', views.submit_policy, name='submit_policy'),
    path('archive-policy/<int:pk>', views.archive_policy, name='archive_policy'),
]

security/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from model_utils import FieldTracker

# Create your models here.    
class ComplianceStandard(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    reference_url = models.CharField(max_length=100)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Risk(models.Model):
    Severity_Levels = [
        ("LOW", "Low"),
        ("MEDIUM", "Medium"),
        ("HIGH", "High"),
        ("CRITICAL", "Critical"),
    ]

    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    severity = models.CharField(max_length=100, choices=Severity_Levels, default="LOW")
    updated_at = models.DateTimeField(auto_now=True)
    tracker = FieldTracker()

    def __str__(self):
        return self.name
    
class Policy(models.Model):
    Status = [
        ("DRAFT", "Draft"),
        ("IN_REVIEW", "In Review"),
        ("APPROVED", "Approved"),
        ("ACTIVE", "Active"),
        ("ARCHIVED", "Archived"),
    ]

    title = models.CharField(max_length=100)
    content = models.TextField(max_length=250)
    status = models.CharField(max_length=25, choices=Status, default="DRAFT")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    risks = models.ManyToManyField(Risk)
    compliance_standards = models.ManyToManyField(ComplianceStandard)
    tracker = FieldTracker()
    version_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    def submit(self):
        if self.status == "DRAFT": self.status = "IN_REVIEW"
        elif self.status == "IN_REVIEW": self.status = "APPROVED"
        else: self.status = "ACTIVE"
        self.save()
    
    def archive(self):
        self.status = "ARCHIVED"
        self.save()
    
class PolicyVersion(models.Model):
    policy = models.ForeignKey(Policy, on_delete=models.CASCADE)
    version_number = models.IntegerField(default=1)
    title = models.TextField(max_length=250)
    content = models.TextField(max_length=250)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(max_length=250, default="")
    risks = models.ManyToManyField(Risk)
    compliance_standards = models.ManyToManyField(ComplianceStandard)

    def __str__(self):
        return self.policy.title + "-" + str(self.version_number) 
    
class PolicyAcknowledgment(models.Model):
    policy = models.ForeignKey(Policy, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    acknowledged_at = models.DateTimeField(auto_now_add=True)

security/forms.py
from django import forms
from .models import Policy, Risk, PolicyVersion, ComplianceStandard

class PolicyForm(forms.ModelForm):
    class Meta:
        model = Policy
        fields = ["title", "content", "risks", "compliance_standards"]
        widgets = {
            'risks': forms.CheckboxSelectMultiple(),
            'compliance_standards': forms.CheckboxSelectMultiple(),
        }

class RiskForm(forms.ModelForm):
    class Meta:
        model = Risk
        fields = ["name", "description", "severity"]

class ComplianceStandardForm(forms.ModelForm):
    class Meta:
        model = ComplianceStandard
        fields = ["name", "description", "reference_url"]

class PolicyVersionForm(forms.ModelForm):
    class Meta:
        model = PolicyVersion
        fields = ["notes"]

security/views.py
from django.shortcuts import render, redirect
from .forms import PolicyForm, RiskForm, PolicyVersionForm, ComplianceStandardForm
from django.contrib.auth.decorators import login_required, permission_required
from .models import Policy, Risk, PolicyVersion, ComplianceStandard, PolicyAcknowledgment
from django.contrib import messages
from .generate_excel import generatePolicyAcknowledgementReport

# Create your views here.
@login_required(login_url="/login")
@permission_required(["security.view_policy", "security.delete_policy"], login_url="/access-denied")
def view_policies(request):
    policies = Policy.objects.all()
    
    if request.method == "POST":
        policy_id_delete = request.POST.get("policy-id-delete")
        policy_id_edit = request.POST.get("policy-id-edit")
        if policy_id_delete:
            policy = Policy.objects.filter(id=policy_id_delete).first()
            if policy:
                policy.delete()
                messages.success(request, "The policy was deleted successfully.")
        else:
            policy = Policy.objects.filter(id=policy_id_edit).first()
            return redirect("/edit-policy", pk=policy.id)


    return render(request, 'security/list_policy.html', {"policies": policies})

def create_policy_version(policy: Policy, request):
    new_policy_version = PolicyVersion(title = policy.title, content = policy.content, version_number = policy.version_count + 1, policy = policy, created_by = request.user)
    new_policy_version.save()
    related_risks = Risk.objects.filter(policy = policy.id)
    new_policy_version.risks.add(*related_risks)
    related_compliance_standards = ComplianceStandard.objects.filter(policy = policy.id)
    new_policy_version.compliance_standards.add(*related_compliance_standards)
    new_policy_version.save()
    policy.version_count = policy.version_count + 1
    policy.save()
    return new_policy_version

def check_policy_risks_changes(policy: Policy, related_risks_ids, request, policy_version):
    current_related_risks_ids = [risk.id for risk in policy.risks.all()]
    if (set(related_risks_ids) != set(current_related_risks_ids)):
        if policy_version == False:
            create_policy_version(policy, request)
            messages.success(request, "A new version of the policy has been created.")

        if policy_version:
            policy_version.risks.add(*policy.risks.all())

def check_policy_compliance_standards_changes(policy: Policy, related_compliance_standards_ids, request, policy_version):
    current_related_compliance_standards_ids = [compliance_standard.id for compliance_standard in policy.compliance_standards.all()]
    if (set(related_compliance_standards_ids) != set(current_related_compliance_standards_ids)):
        if policy_version == False:
            create_policy_version(policy, request)
            messages.success(request, "A new version of the policy has been created.")

        if policy_version:
            policy_version.compliance_standards.add(*policy.compliance_standards.all())

@login_required(login_url="/login")
@permission_required("security.add_policy", login_url="/access-denied")
def create_policy(request):
    if request.method == 'POST':
        form = PolicyForm(request.POST)
        if form.is_valid():
            policy = form.save(commit=False)
            policy.created_by = request.user
            policy.save()
            form.save_m2m()
            create_policy_version(policy, request)
            messages.success(request, "The policy was created successfully.")
            return redirect("/policy-list")
    else:
        form = PolicyForm()
    
    return render(request, 'security/create_policy.html', {"form": form})

@login_required(login_url="/login")
@permission_required("security.change_policy", login_url="/access-denied")
def edit_policy(request, pk):
    policy = Policy.objects.get(id=pk)
    policy_version = False
    if request.method == 'POST':
        form = PolicyForm(request.POST, instance=policy)
        if form.is_valid():
            related_risks_ids = [risk.id for risk in Risk.objects.filter(policy = policy.id)]
            related_compliance_standards_ids = [compliance_standard.id for compliance_standard in ComplianceStandard.objects.filter(policy = policy.id)]
            if policy.tracker.changed():
                policy_version = create_policy_version(policy, request)
                messages.success(request, "A new version of the policy has been created.")
                created_version = True
            form.save()
            check_policy_risks_changes(policy, related_risks_ids, request, policy_version)
            check_policy_compliance_standards_changes(policy, related_compliance_standards_ids, request, policy_version)
            messages.success(request, "The policy was edited successfully.")
            return redirect("/policy-list")
    else:
        form = PolicyForm(instance=policy)
        context = {
            'form': form,
        }
    
    return render(request, 'security/edit_policy.html', {"form": form})

@login_required(login_url="/login")
@permission_required(["security.view_risk", "security.delete_risk"], login_url="/access-denied")
def view_risks(request):
    risks = Risk.objects.all()
    
    if request.method == "POST":
        risk_id_delete = request.POST.get("risk-id-delete")
        risk_id_edit = request.POST.get("risk-id-edit")
        if risk_id_delete:
            risk = Policy.objects.filter(id=risk_id_delete).first()
            if risk:
                risk.delete()
                messages.success(request, "The risk was deleted successfully.")
        else:
            risk = Policy.objects.filter(id=risk_id_edit).first()
            return redirect("/edit-risk", pk=risk.id)


    return render(request, 'security/list_risk.html', {"risks": risks})

@login_required(login_url="/login")
@permission_required("security.add_risk", login_url="/access-denied")
def create_risk(request):
    if request.method == 'POST':
        form = RiskForm(request.POST)
        if form.is_valid():
            risk = form.save(commit=False)
            risk.created_by = request.user
            risk.save()
            messages.success(request, "The risk was created successfully.")
            return redirect("/risk-list")
    else:
        form = RiskForm()
    
    return render(request, 'security/create_risk.html', {"form": form})

@login_required(login_url="/login")
@permission_required("security.change_risk", login_url="/access-denied")
def edit_risk(request, pk):
    risk = Risk.objects.get(id=pk)
    if request.method == 'POST':
        form = RiskForm(request.POST, instance=risk)
        if form.is_valid():
            form.save()
            messages.success(request, "The risk was edited successfully.")
            return redirect("/risk-list")
    else:
        form = RiskForm(instance=risk)
        context = {
            'form': form,
        }
    
    return render(request, 'security/edit_risk.html', {"form": form})

@login_required(login_url="/login")
@permission_required(["security.view_compliancestandard", "security.delete_compliancestandard"], login_url="/access-denied")
def view_compliance_standard(request):
    compliance_standards = ComplianceStandard.objects.all()
    
    if request.method == "POST":
        compliance_standard_id_delete = request.POST.get("compliance-standard-id-delete")
        compliance_standard_id_edit = request.POST.get("compliance-standard-id-edit")
        if compliance_standard_id_delete:
            compliance_standard = ComplianceStandard.objects.filter(id=compliance_standard_id_delete).first()
            if compliance_standard:
                compliance_standard.delete()
                messages.success(request, "The compliance standard was deleted successfully.")
        else:
            compliance_standard = Policy.objects.filter(id=compliance_standard_id_edit).first()
            return redirect("/edit-compliance-standard", pk=compliance_standard.id)


    return render(request, 'security/list_compliance_standard.html', {"compliance_standards": compliance_standards})

@login_required(login_url="/login")
@permission_required("security.add_compliancestandard", login_url="/access-denied")
def create_compliance_standard(request):
    if request.method == 'POST':
        form = ComplianceStandardForm(request.POST)
        if form.is_valid():
            compliance_standard = form.save(commit=False)
            if compliance_standard.reference_url[:8] != "https://": compliance_standard.reference_url = "https://" + compliance_standard.reference_url
            form.save()
            messages.success(request, "The compliance standard was created successfully.")
            return redirect("/compliance-standard-list")
    else:
        form = ComplianceStandardForm()
    
    return render(request, 'security/create_compliance_standard.html', {"form": form})

@login_required(login_url="/login")
@permission_required("security.change_compliancestandard", login_url="/access-denied")
def edit_compliance_standard(request, pk):
    compliance_standard = ComplianceStandard.objects.get(id=pk)
    if request.method == 'POST':
        form = ComplianceStandardForm(request.POST, instance=compliance_standard)
        if form.is_valid():
            compliance_standard = form.save(commit=False)
            if compliance_standard.reference_url[:8] != "https://": compliance_standard.reference_url = "https://" + compliance_standard.reference_url
            form.save()
            messages.success(request, "The compliance standard was edited successfully.")
            return redirect("/compliance-standard-list")
    else:
        form = ComplianceStandardForm(instance=compliance_standard)
        context = {
            'form': form,
        }
    
    return render(request, 'security/edit_compliance_standard.html', {"form": form})

@login_required(login_url="/login")

security/templates/security/create_compliance_standard.html
{% extends 'main/base.html' %}
{% block title %}Create a Compliance Standard{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}{{form|crispy}}
    <button type="submit" class="btn btn-success">Create</button>
</form>
{% endblock %}

security/templates/security/create_risk.html
{% extends 'main/base.html' %}
{% block title %}Create a Risk{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}{{form|crispy}}
    <button type="submit" class="btn btn-success">Create</button>
</form>
{% endblock %}

security/templates/security/edit_compliance_standard.html
{% extends 'main/base.html' %}
{% block title %}Edit Compliance Standard{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}{{form|crispy}}
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock %}

security/templates/security/edit_policy.html
{% extends 'main/base.html' %}
{% block title %}Edit Policy{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}{{form|crispy}}
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock %}

security/templates/security/list_policy.html
{% extends 'main/base.html' %}
{% block title %}View Policies{% endblock %}
{% block content %}
<div class="text-end">
    <a class="btn btn-success" href="/create-policy">Create New Policy</a>
</div>
<br/>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
{% for policy in policies %}
<div class="card mt-2">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6"><span class="badge bg-dark text-left">{{policy.get_status_display}}</span></div>
            <div class="text-end col-md-6">Created by: <strong>{{ policy.created_by.first_name }} {{ policy.created_by.last_name }}</strong></div>
        </div>
    </div>
    <div class="card-body d-flex flex-row justify-content-between">
        <div class="card-title">
            <h5>{{ policy.title }}</h5>
            <span>Risks: </span>
            {% for risk in policy.risks.all %}
                <span class="badge rounded-pill {{risk.get_severity_display.lower}}-severity">{{risk.name}}</span>
            {% endfor %}
        </div>
        <div>
            <form method="post">
                {% csrf_token %}
                {% if perms.security.delete_policy %}
                <button type="submit" class="btn btn-danger" name="policy-id-delete" value="{{policy.id}}">Delete</button>
                {% endif %}
                {% if perms.security.change_policy %}
                <a class="btn btn-warning" href="{% url 'edit_policy' policy.pk %}">Edit</a>
                {% endif %}
                {% if perms.security.view_policyversion %}
                <a class="btn btn-primary" href="{% url 'view_policy_versions' policy.pk %}">View Versions</a>
                {% endif %}
                {% if perms.security.view_policyacknowledgment %}
                <a class="btn btn-outline-primary" href="{% url 'view_policy' policy.pk %}">View</a>
                {% endif %}
                {% if perms.security.view_policyacknowledgment %}
                <a class="btn btn-outline-primary" href="{% url 'view_policy_acknowledgments' policy.pk %}">View Policy Acknowledgments</a>
                {% endif %}
            </form>
        </div>
    </div>
    <div class="card-footer">Created at: {{ policy.created_at }}</div>
    <div class="card-footer">Last Updated at: {{ policy.updated_at }}</div>
</div>
<br/>
{% empty %}
<p>No policies available.</p>
{% endfor %}
{% endblock %}

security/templates/security/list_policy_acknowledgment.html
{% extends 'main/base.html' %}
{% block title %}View Policy Acknowledgments{% endblock %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
<div class="container">
<div class="row">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Unacknowledged Policies</th>
                </tr>
            </thead>
            <tbody>
                {% for policy in unacknowledged_policies %}
                <tr><td>
                <div class="card mt-2">
                    <div class="card-header text-end">Created by: <strong>{{ policy.created_by.first_name }} {{ policy.created_by.last_name }}</strong></div>
                    <div class="card-body d-flex flex-row justify-content-between">
                        <div class="card-title">
                            <h5>{{ policy.title }}</h5>
                            <span>Risks: </span>
                            {% for risk in policy.risks.all %}
                                <span class="badge rounded-pill {{risk.get_severity_display.lower}}-severity">{{risk.name}}</span>
                            {% endfor %}
                        </div>
                        <div>
                            <form method="post">
                                {% csrf_token %}
                                {% if perms.security.change_policyacknowledgment %}
                                <button type="submit" class="btn btn-primary" name="policy-id-acknowledge" value="{{policy.id}}">Acknowledge</button>
                                {% endif %}
                                {% if perms.security.view_policyacknowledgment %}
                                <button type="submit" class="btn btn-outline-primary" name="policy-id-view" value="{{policy.id}}">View</button>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                    <div class="card-footer">Created at: {{ policy.created_at }}</div>
                    <div class="card-footer">Last Updated at: {{ policy.updated_at }}</div>
                </div>
                </td></tr>
                {% empty %}
                    <tr><td>No unacknowledged policies available.</td></tr>
                {% endfor %}
            </tbody>
            </table>
    </div>
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Acknowledged Policies</th>
                </tr>
            </thead>
            <tbody>
                {% for policy in acknowledged_policies %}
                <tr><td>
                <div class="card mt-2">
                    <div class="card-header text-end">Created by: <strong>{{ policy.created_by.first_name }} {{ policy.created_by.last_name }}</strong></div>
                    <div class="card-body d-flex flex-row justify-content-between">
                        <div class="card-title">
                            <h5>{{ policy.title }}</h5>
                            <span>Risks: </span>
                            {% for risk in policy.risks.all %}
                                <span class="badge rounded-pill {{risk.get_severity_display.lower}}-severity">{{risk.name}}</span>
                            {% endfor %}
                        </div>
                        <div>
                            <form method="post">
                                {% csrf_token %}
                                {% if perms.security.view_policyacknowledgment %}
                                <button type="submit" class="btn btn-outline-primary" name="policy-id-view" value="{{policy.id}}">View</button>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                    <div class="card-footer">Created at: {{ policy.created_at }}</div>
                    <div class="card-footer">Last Updated at: {{ policy.updated_at }}</div>
                </div>
                </td></tr>
                {% empty %}
                    <tr><td>No acknowledged policies available.</td></tr>
                {% endfor %}
            </tbody>
            </table>
    </div>
</div>
{% endblock %}

security/templates/security/list_policy_version.html
{% extends 'main/base.html' %}
{% block title %}View Policy Versions{% endblock %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
{% for policy_version in policy_versions %}
<div class="card mt-2">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6"><span class="badge rounded-pill text-left version-badge">Version {{policy_version.version_number}}</span></div>
            <div class="text-end col-md-6">Created by: <strong>{{ policy_version.created_by.first_name }} {{ policy_version.created_by.last_name }}</strong></div>
        </div>
    </div>
    <div class="card-body d-flex flex-row justify-content-between">
        <div class="card-title">
            <h5>{{ policy_version.title }}</h5>
            <span>Risks: </span>
            {% for risk in policy_version.risks.all %}
                <span class="badge rounded-pill {{risk.get_severity_display.lower}}-severity">{{risk.name}}</span>
            {% endfor %}
        </div>
        <div>
            <form method="post">
                {% csrf_token %}
                {% if perms.security.delete_policyversion %}
                <button type="submit" class="btn btn-danger" name="policy-version-id-delete" value="{{policy_version.id}}">Delete</button>
                {% endif %}
                {% if perms.security.change_policyversion %}
                <a class="btn btn-outline-primary" href="{% url 'edit_policy_version' policy_version.pk %}">Add Note</a>
                {% endif %}
                {% if perms.security.view_policyversion %}
                <a class="btn btn-primary" href="{% url 'view_policy_version' policy_version.pk %}">View</a>
                {% endif %}
                {% if perms.security.change_policy %}
                <a class="btn btn-outline-dark" href="{% url 'rollback_policy_version' policy_version.pk %}">Rollback</a>
                {% endif %}
            </form>
        </div>
    </div>
    <div class="card-footer">Created at: {{ policy_version.created_at }}</div>
</div>
<br/>
{% empty %}
<p>No policy versions available.</p>
{% endfor %}
{% endblock %}

security/templates/security/list_risk.html
{% extends 'main/base.html' %}
{% block title %}View Risks{% endblock %}
{% block content %}
<div class="text-end">
    <a class="btn btn-success" href="/create-risk">Create New Risk</a>
</div>
<br/>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
{% for risk in risks %}
<div class="card mt-2">
    <div class="card-body d-flex flex-row justify-content-between">
        <div class="card-title">
            <h5>{{ risk.name }}</h5>
            <span style="white-space: pre-line">{{ risk.description }}</span>
            <br/>
            <span style="white-space: pre-line">Severity: </span>
            <span class="badge rounded-pill {{risk.get_severity_display.lower}}-severity">{{risk.get_severity_display}}</span>
        </div>
        <div>
            <form method="post">
                {% csrf_token %}
                {% if perms.security.delete_risk %}
                <button type="submit" class="btn btn-danger" name="risk-id-delete" value="{{risk.id}}">Delete</button>
                {% endif %}
                {% if perms.security.change_risk %}
                <a class="btn btn-warning" href="{% url 'edit_risk' risk.pk %}">Edit</a>
                {% endif %}
            </form>
        </div>
    </div>
    <div class="card-footer">Last Updated at: {{ risk.updated_at }}</div>
</div>
<br/>
{% empty %}
<p>No risks available.</p>
{% endfor %}
{% endblock %}

security/templates/security/view_policy.html
{% extends 'main/base.html' %}
{% block title %}View Policy Version{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
<div class="form-group">
    <div class="mb-3">
        <label class="form-label">Title</label>
        <input class="form-control" value="{{ policy.title }}" readonly>
    </div>
    <div class="mb-3">
        <label class="form-label">Content</label>
        <textarea class="textarea form-control" rows="10" cols="40" readonly>{{ policy.content }}</textarea>
    </div>
    <div class="mb-3">
        <label class="form-label">Version Number</label>
        <br/><span class="badge rounded-pill text-left version-badge">Version {{policy.version_number}}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Status</label>
        <input class="form-control" value="{{ policy.get_status_display }}" readonly>
    </div>
    <div class="mb-3">
        <label class="form-label">Risks</label><br/>
        {% for risk in policy.risks.all %}
        <span class="badge rounded-pill {{risk.get_severity_display.lower}}-severity">{{risk.name}}</span>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label class="form-label">Compliance Standards</label><br/>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
              </tr>
            </thead>
            <tbody>
            {% for compliance_standard in policy.compliance_standards.all %}
                <tr>
                    <td><a target="_blank" href="{{ compliance_standard.reference_url }}">{{compliance_standard.name}}</a></td>
                    <td>{{ compliance_standard.description }}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
    </div>
    {% if user.groups.all.0.name == 'Manager' %}
        {% if policy.status != 'ACTIVE' %}
            <div class="text-end">
                <a class="btn btn-primary" href="{% url 'submit_policy' policy.pk %}">Submit</a>
            </div>
        {% endif %}
        {% if policy.status == 'ACTIVE' %}
            <div class="text-end">
                <a class="btn btn-danger" href="{% url 'archive_policy' policy.pk %}">Archive</a>
            </div>
        {% endif %}
    {% endif %}
</div>
{% endblock %}